Code.require_file("examples/fellow.exs")
Code.require_file("examples/bro.exs")
Code.require_file("examples/man_asc.exs")
Code.require_file("examples/man_desc.exs")
Code.require_file("examples/buddy.exs")
ExUnit.start()
