version: '3'
services:
  web:
    build: .
    volumes:
      - .:/code
      - .:/$PWD
      - ~/.aws:/home/app/.aws
    working_dir: /code
    networks:
      - default
    env_file:
      - biscuit.env
    depends_on:
      - redis

  redis:
    image: public.ecr.aws/bitnami/redis:5.0
